### ISSUE TITLE
Suggestion: split up lib into different workspaces with their own package.json

### ISSUE THREAD

**Issue by oveddan** [bhouston/behave-graph#128]
I would suggest splitting up this monorepo into multiple workspaces within the monorepo, each with its own package.json.  

I would like to do an implementation of ThreeScene using `@react-three/fiber` but I don't wan't to pollute the dependencies in the main package.json with those dependencies.  So I think it would make sense to have each of the following workspaces, each with their own package.jsons:

* one that defines the json schema/standard for this behavior-graph data format
* a lib with the current implementation to parse it. - this can be imported directly using npmjs without needing to import `three.js`
* a folder for 3d scene functionality with `three.js` as a dependency.
* different folders for different example implementations - one for three.js and one for @react-three/fiber
* eventually a folder could be created for unity implementation

**Comment by bhouston** [comment]
I would love that.  I am not good at that unfortunately so I have focused on just making progress on the core capabilities rather than mono-repo refactoring.  How much work is that to do?  Could you propose something?

BTW there is no core dependencies on threeify or three.js for parsing or executing graphs right now.  They are dev-dependencies only as I only need them for the examples.  And right now I do have the Three.js integration code in the three.js example.  That isn't great.

**Comment by oveddan** [comment]
Hey I've gotten around to setting this up in another repo and have figured out what could be a nice and easy way to do it; I used the `@react-three/fiber` repo as an example.

I would propose:
* Separating the 1examples from the `core` framework (such as lib), each having their own package.json in a subfolder
* Setting up workspaces in the root.
* Setting up [preconstruct](https://preconstruct.tools/) as part of the dev/build/run process, which makes it much easier in monorepos to refernece other libs in the same worksapce.  For exampe it makes it easy for the example/front-end code to reference the `behavior-graph` lib.  You could get rid of the step of needing to run `export-node-spec`.

I can open a PR with what this would look like for your feedback

**Comment by bhouston** [comment]
this is done!
