### ISSUE TITLE
Implement Switch

### ISSUE THREAD

**Issue by aitorllj93** [bhouston/behave-graph#190]
Hi, first of all, thank you for your work, this library looks promising.  I'm trying to figure out how to implement a **Switch** Flow. To do that we should be able to define a variable number of in/out sockets and I don't know if that's possible with current implementation

**Comment by bhouston** [comment]
It is definitely possible.  Look at sequence that has a variable number of outputs.  Just take that pattern and expand it to the inputs.  Note that right now I do not treat nodes within the execution system has having dynamic number of inputs/outputs, but that is because they are not actually dynamic at run-time.  They are only dynamic within an editor interface and I believe that can be done just by redeclaring the node with different number of inputs/outputs and copying across the preset values/links -- basically doing a replace.  This reduces the complexity of the system.

**Comment by aitorllj93** [comment]
@bhouston thanks for the answer. So given the following approach:
https://docs.unrealengine.com/4.27/en-US/BlueprintAPI/Utilities/FlowControl/Switch/SwitchonString/
![image](https://user-images.githubusercontent.com/5903438/208128582-8624406f-eaff-4ca0-b5bc-a6792b5eba4e.png)

How should I declare the Node sockets?

**Comment by bhouston** [comment]
Here is a quick attempt at it: https://github.com/bhouston/behave-graph/pull/195

I haven't yet tested it.  To do that I need to make a graph.json file that runs it.
